server.port=${PORT:8080}
spring.application.name=todos-api
spring.profiles.active=dev

spring.jpa.open-in-view=false
spring.mvc.problemdetails.enabled=true

app.jwt.issuer=todos-api
app.jwt.expiry-minutes=60